include: package:very_good_analysis/analysis_options.7.0.0.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    avoid_catches_without_on_clauses: false

analyzer:
  errors:
    invalid_annotation_target: ignore
    inference_failure_on_collection_literal: info
    avoid_multiple_declarations_per_line: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"